### ISSUE TITLE
Update value icons

### ISSUE THREAD

**Issue by Tannybunny** [consento-org/consento-website#71]
Change the value icons to icons we made

**Comment by Tannybunny** [comment]
Value icons were updated, now they should be scaled up a little bit for example to 
```css
#icon_area img {
    max-height: 120px;
}
```

?

@Torgian
